export const dxButtonConfig = {

    // icon
    add_icon: 'fa fa-plus',
    delete_icon: 'fa fa-trash',
    menu_icon: 'fa fa-bars',
    edit_icon: 'fa fa-pencil',
    close_icon: 'fa fa-times',
    cancel_icon: 'fa fa-times',
    return_icon: 'fa fa-undo',
    save_icon: 'fa fa-save',
    print_icon: 'fa fa-print',
    search_icon: 'fa fa-search',
    back_icon: 'arrowleft',
    plus_icon: 'fa fa-plus',
    release_icon: 'fa fa-pen-alt',
    confirm_icon: 'fa fa-check',
    approve_icon: 'check',
    unapprove_icon: 'undo',
    view_icon: 'arrowright',
    public_icon: 'group',
    list_icon: 'bulletlist',
    exportExcel_icon: 'exportxlsx',
    exportDoc_icon: 'docfile',
    merge_icon: 'fa fa-compress',
    import_icon: 'arrowright',

    //type
    slide_type: 'normal',
    add_type: 'default',
    delete_type: 'danger',
    close_type: 'normal',
    cancel_type: 'danger',
    return_type: 'normal',
    menu_type: 'default',
    edit_type: 'normal',
    save_type: 'default',
    print_type: 'default',
    search_type: 'default',
    back_type: 'back',
    danger_type: 'danger',
    confirm_type: 'default',
    view_type: 'default',
    approve_type: 'default',
    unapprove_type: 'normal',
    public_type: 'default',
    onlyIcon_type: 'back',
    list_type: 'default',
    exportExcel_type: 'success',
    exportDoc_type: 'default',

    //mode
    contained_StylingMode: 'contained', // 'outlined',
    text_StylingMode: 'text',
    outlined_StylingMode: 'outlined',
    underlined_StylingMode: 'underlined'
  };
